version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: logitrack_postgres
    restart: always
    environment:
      POSTGRES_USER: logitrack_user
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: logitrack_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: