"""add idempotency request_hash and user_id

Revision ID: 32d732eed210
Revises: 4ba6182e4689
Create Date: 2026-08-20 17:45:25.013024

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '32d732eed210'
down_revision: str | None = '4ba6182e4689'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idempotency_keys', sa.Column('request_hash', sa.String(length=64), server_default='', nullable=False))
    op.add_column('idempotency_keys', sa.Column('user_id', sa.Integer(), server_default='0', nullable=False))
    op.alter_column('idempotency_keys', 'response_body',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('idempotency_keys', 'response_body',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_column('idempotency_keys', 'user_id')
    op.drop_column('idempotency_keys', 'request_hash')
    # ### end Alembic commands ###
